dist: trusty
language: generic

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt56-trusty
  - sudo apt-get update
  - sudo apt-get -y install qt56tools qt56svg

script:
  - source /opt/qt56/bin/qt56-env.sh
  - cmake . && make
  - git clean -xfd
