sudo: required
dist: trusty
language: generic

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt58-trusty
  - sudo apt-get update
  - sudo apt-get -y install qt58tools qt58svg libfreetype6-dev libfontconfig1-dev
  - wget https://poppler.freedesktop.org/poppler-0.50.0.tar.xz
  - tar -xvJf poppler-0.50.0.tar.xz
  - source /opt/qt58/bin/qt58-env.sh
  - pushd poppler-0.50.0 && cmake -DCMAKE_INSTALL_PREFIX=/usr && make && sudo make install && popd

script:
  - source /opt/qt58/bin/qt58-env.sh
  - cmake . && make
  - git clean -xfd
